'use strict';
const $ = (id) => document.getElementById(id);
const canvas = $('workCanvas');
const ctx = canvas.getContext('2d', { willReadFrequently: true });
const state = {
  tool: 'keep', image: null, imageDataUrl: '', layers: [],
  colors: ['#0b0b0b','#333333','#666666','#999999','#cfcfcf','#ffffff','#ff5c9b','#8d5cff','#53c7ff','#79e096','#ffd166','#f8961e'],
  drawing: false, last: null, deferredPrompt: null
};
function setStatus(msg){ $('status').textContent = msg; }
function clearCanvas(message='Ready. Upload a photo or describe an idea.'){ ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#111'; ctx.textAlign='center'; ctx.font='700 44px system-ui'; ctx.fillText('StencilForge', canvas.width/2, 285); ctx.font='22px system-ui'; ctx.fillText('Upload photo or describe idea', canvas.width/2, 330); ctx.textAlign='left'; state.layers=[]; renderPreviews(); setStatus(message); }
function drawImageFit(){ if(!state.image) return; ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); const s=Math.min(canvas.width/state.image.width, canvas.height/state.image.height); const w=state.image.width*s, h=state.image.height*s; ctx.drawImage(state.image,(canvas.width-w)/2,(canvas.height-h)/2,w,h); setStatus('Image loaded. Use Keep/Remove brush, then make stencil layers.'); }
function rebuildLayerControls(){ const count=Number($('layerCount').value); $('layerCountValue').textContent=count; const box=$('layerControls'); box.innerHTML=''; for(let i=0;i<count;i++){ const row=document.createElement('div'); row.className='layerRow'; row.innerHTML=`<div class="swatch" style="background:${state.colors[i]}"></div><strong>Layer ${i+1}</strong><input type="color" value="${state.colors[i]}" data-color="${i}"><input title="Visible" type="checkbox" checked data-vis="${i}">`; box.appendChild(row); } box.querySelectorAll('[data-color]').forEach(input=>input.addEventListener('input',e=>{ const i=Number(e.target.dataset.color); state.colors[i]=e.target.value; e.target.closest('.layerRow').querySelector('.swatch').style.background=e.target.value; rebuildLayerSvgs(); renderPreviews(); })); }
function setSource(source){ $('photoPane').classList.toggle('hidden', source!=='photo'); $('ideaPane').classList.toggle('hidden', source!=='idea'); $('sourcePhoto').classList.toggle('active', source==='photo'); $('sourceIdea').classList.toggle('active', source==='idea'); }
function setTool(tool){ state.tool=tool; $('keepTool').classList.toggle('primary',tool==='keep'); $('removeTool').classList.toggle('primary',tool==='remove'); }
function pos(e){ const r=canvas.getBoundingClientRect(); const p=e.touches ? e.touches[0] : e; return {x:(p.clientX-r.left)*canvas.width/r.width, y:(p.clientY-r.top)*canvas.height/r.height}; }
function drawBrush(e){ if(!state.drawing) return; e.preventDefault(); const p=pos(e), b=Number($('brushSize').value); ctx.save(); ctx.globalCompositeOperation = state.tool==='remove' ? 'destination-out' : 'source-over'; ctx.strokeStyle = state.tool==='remove' ? 'rgba(255,255,255,1)' : 'rgba(0,0,0,.95)'; ctx.fillStyle = ctx.strokeStyle; ctx.lineWidth = b*2; ctx.lineCap = 'round'; if(state.last){ ctx.beginPath(); ctx.moveTo(state.last.x,state.last.y); ctx.lineTo(p.x,p.y); ctx.stroke(); } else { ctx.beginPath(); ctx.arc(p.x,p.y,b,0,Math.PI*2); ctx.fill(); } ctx.restore(); state.last=p; }
function generateIdea(){ const text=($('ideaText').value || 'stencil idea').trim(); const style=$('styleSelect').value; ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.strokeStyle='#111'; ctx.fillStyle='#111'; ctx.lineCap='round'; ctx.lineJoin='round'; const cx=canvas.width/2, cy=canvas.height/2; ctx.lineWidth = style==='clean' ? 16 : style==='tattoo' ? 10 : 12; ctx.beginPath(); ctx.ellipse(cx,cy,220,160,0,0,Math.PI*2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(cx-190,cy+115); ctx.quadraticCurveTo(cx,cy+250,cx+190,cy+115); ctx.stroke(); if(style==='tattoo'){ for(let i=0;i<12;i++){ const a=i*Math.PI/6; ctx.beginPath(); ctx.moveTo(cx+245*Math.cos(a),cy+185*Math.sin(a)); ctx.lineTo(cx+285*Math.cos(a),cy+215*Math.sin(a)); ctx.stroke(); }} if(style==='graffiti'){ ctx.font='900 72px system-ui'; } else { ctx.font='900 50px system-ui'; } ctx.textAlign='center'; const words=text.split(/\s+/).slice(0,4).join(' '); ctx.fillText(words,cx,cy+12); ctx.font='24px system-ui'; ctx.fillText(style.replace(/^./,m=>m.toUpperCase()),cx,cy+58); ctx.textAlign='left'; state.image=null; state.imageDataUrl=''; setStatus('Local idea sketch made. Edit it, then make layers.'); }
function getBrightnessData(step){ const data=ctx.getImageData(0,0,canvas.width,canvas.height).data; const w=Math.ceil(canvas.width/step), h=Math.ceil(canvas.height/step); const bright=Array.from({length:h},()=>Array(w).fill(255)); for(let y=0;y<h;y++){ for(let x=0;x<w;x++){ const px=Math.min(canvas.width-1,x*step), py=Math.min(canvas.height-1,y*step); const i=(py*canvas.width+px)*4; bright[y][x]=(data[i]*0.299+data[i+1]*0.587+data[i+2]*0.114); }} return bright; }
function makeBitmap(bright, threshold){ const h=bright.length,w=bright[0].length; const bm=Array.from({length:h},()=>Array(w).fill(0)); for(let y=0;y<h;y++) for(let x=0;x<w;x++) bm[y][x]=bright[y][x] <= threshold ? 1 : 0; return bm; }
function bridgeBitmap(bm){ if(!$('autoBridge').checked) return bm; const h=bm.length,w=bm[0].length, seen=Array.from({length:h},()=>Array(w).fill(false)), comps=[]; const dirs=[[1,0],[-1,0],[0,1],[0,-1]]; for(let y=0;y<h;y++) for(let x=0;x<w;x++) if(bm[y][x] && !seen[y][x]){ const q=[[x,y]], cells=[]; let sx=0,sy=0; seen[y][x]=true; while(q.length){ const [a,b]=q.pop(); cells.push([a,b]); sx+=a; sy+=b; for(const [dx,dy] of dirs){ const nx=a+dx,ny=b+dy; if(nx>=0&&ny>=0&&nx<w&&ny<h&&bm[ny][nx]&&!seen[ny][nx]){seen[ny][nx]=true;q.push([nx,ny]);}} } comps.push({cells,cx:sx/cells.length,cy:sy/cells.length}); }
  if(comps.length<2) return bm; comps.sort((a,b)=>b.cells.length-a.cells.length); const main=comps[0]; const thick=Number($('bridgeSize').value); for(let k=1;k<comps.length;k++){ const part=comps[k]; let bestA=main.cells[0], bestB=part.cells[0], best=Infinity; const sampleA=main.cells.filter((_,i)=>i%Math.max(1,Math.floor(main.cells.length/80))===0); const sampleB=part.cells.filter((_,i)=>i%Math.max(1,Math.floor(part.cells.length/80))===0); for(const a of sampleA){ for(const b of sampleB){ const d=(a[0]-b[0])**2+(a[1]-b[1])**2; if(d<best){best=d;bestA=a;bestB=b;} }} drawBridge(bm,bestA[0],bestA[1],bestB[0],bestB[1],thick); main.cells.push(...part.cells); }
  return bm; }
function drawBridge(bm,x0,y0,x1,y1,thick){ const h=bm.length,w=bm[0].length; const n=Math.max(1,Math.abs(x1-x0),Math.abs(y1-y0)); for(let i=0;i<=n;i++){ const x=Math.round(x0+(x1-x0)*i/n), y=Math.round(y0+(y1-y0)*i/n); for(let yy=-thick;yy<=thick;yy++) for(let xx=-thick;xx<=thick;xx++){ if(xx*xx+yy*yy<=thick*thick){ const nx=x+xx,ny=y+yy; if(nx>=0&&ny>=0&&nx<w&&ny<h) bm[ny][nx]=1; }}} }
function bitmapToPath(bm,step){ let d=''; const h=bm.length,w=bm[0].length; for(let y=0;y<h;y++) for(let x=0;x<w;x++) if(bm[y][x]) d+=`M${x*step} ${y*step}h${step}v${step}h-${step}z`; return d; }
function svgForPath(path,color,title){ const marks = $('registrationMarks').checked ? `<g fill="none" stroke="#000" stroke-width="2"><circle cx="30" cy="30" r="12"/><circle cx="870" cy="30" r="12"/><circle cx="30" cy="620" r="12"/><circle cx="870" cy="620" r="12"/></g>` : ''; return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650"><title>${escapeXml(title)}</title><rect width="900" height="650" fill="none"/><path d="${path}" fill="${color}" stroke="${color}" stroke-width="0.2" fill-rule="nonzero"/>${marks}</svg>`; }
function escapeXml(s){ return String(s).replace(/[<>&'\"]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[m])); }
function makeLayers(){ const count=Number($('layerCount').value), step=Number($('detailLevel').value); const bright=getBrightnessData(step); state.layers=[]; for(let i=0;i<count;i++){ const threshold = 245 - ((i+1) * (220/count)); const bm=bridgeBitmap(makeBitmap(bright,threshold)); const path=bitmapToPath(bm,step); state.layers.push({name:`layer_${String(i+1).padStart(2,'0')}.svg`, path, svg:svgForPath(path,state.colors[i],`StencilForge Layer ${i+1}`)}); } renderPreviews(); setStatus(`Made ${count} SVG stencil layers. Download from the right panel.`); }
function rebuildLayerSvgs(){ state.layers.forEach((l,i)=>{ l.svg=svgForPath(l.path,state.colors[i],`StencilForge Layer ${i+1}`); }); }
function renderPreviews(){ const box=$('previews'); box.innerHTML=''; if(!state.layers.length){ box.innerHTML='<p class="hint">No layers yet. Make stencil layers to preview them here.</p>'; return; } state.layers.forEach((l,i)=>{ const div=document.createElement('div'); div.className='mini'; div.innerHTML=l.svg; div.title=`Layer ${i+1}`; box.appendChild(div); }); }
function downloadFile(filename,text,mime='image/svg+xml'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:mime})); a.download=filename; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function safeName(){ return ($('projectName').value || 'stencilforge_project').trim().replace(/[^a-z0-9_-]+/gi,'_'); }
function downloadEach(){ if(!state.layers.length){ alert('Make layers first.'); return; } state.layers.forEach((l,i)=>setTimeout(()=>downloadFile(`${safeName()}_${l.name}`,l.svg), i*250)); }
function downloadCombined(){ if(!state.layers.length){ alert('Make layers first.'); return; } const body=state.layers.map((l,i)=>`<path d="${l.path}" fill="${state.colors[i]}" opacity="0.75"/>`).join(''); const marks=$('registrationMarks').checked ? `<g fill="none" stroke="#000" stroke-width="2"><circle cx="30" cy="30" r="12"/><circle cx="870" cy="30" r="12"/><circle cx="30" cy="620" r="12"/><circle cx="870" cy="620" r="12"/></g>`:''; downloadFile(`${safeName()}_combined.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650"><rect width="900" height="650" fill="white"/>${body}${marks}</svg>`); }
function saveProject(){ const payload={projectName:$('projectName').value,colors:state.colors,layers:state.layers,imageDataUrl:state.imageDataUrl}; localStorage.setItem('stencilforge_project',JSON.stringify(payload)); setStatus('Project saved on this device/browser.'); }
function loadProject(){ const raw=localStorage.getItem('stencilforge_project'); if(!raw){ alert('No saved project found.'); return; } const p=JSON.parse(raw); $('projectName').value=p.projectName||'stencilforge_project'; if(Array.isArray(p.colors)) state.colors=p.colors; state.layers=p.layers||[]; rebuildLayerControls(); renderPreviews(); if(p.imageDataUrl){ const im=new Image(); im.onload=()=>{state.image=im;state.imageDataUrl=p.imageDataUrl;drawImageFit();}; im.src=p.imageDataUrl; } setStatus('Saved project loaded.'); }
function init(){ clearCanvas(); rebuildLayerControls(); $('sourcePhoto').onclick=()=>setSource('photo'); $('sourceIdea').onclick=()=>setSource('idea'); $('keepTool').onclick=()=>setTool('keep'); $('removeTool').onclick=()=>setTool('remove'); $('restoreBtn').onclick=()=> state.image ? drawImageFit() : clearCanvas(); $('clearBtn').onclick=()=>clearCanvas('Canvas cleared.'); $('generateIdea').onclick=generateIdea; $('makeLayers').onclick=makeLayers; $('downloadEach').onclick=downloadEach; $('downloadCombined').onclick=downloadCombined; $('saveProject').onclick=saveProject; $('loadProject').onclick=loadProject; $('layerCount').oninput=rebuildLayerControls; $('brushSize').oninput=e=>$('brushValue').textContent=e.target.value; $('bridgeSize').oninput=e=>$('bridgeValue').textContent=e.target.value; $('imageInput').addEventListener('change',e=>{ const f=e.target.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{ const im=new Image(); im.onload=()=>{state.image=im; state.imageDataUrl=r.result; drawImageFit();}; im.src=r.result;}; r.readAsDataURL(f); }); ['mousedown','touchstart'].forEach(ev=>canvas.addEventListener(ev,e=>{state.drawing=true;state.last=null;drawBrush(e);})); ['mousemove','touchmove'].forEach(ev=>canvas.addEventListener(ev,drawBrush,{passive:false})); ['mouseup','mouseleave','touchend','touchcancel'].forEach(ev=>canvas.addEventListener(ev,()=>{state.drawing=false;state.last=null;})); window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('installBtn').classList.remove('hidden');}); $('installBtn').onclick=async()=>{ if(!state.deferredPrompt) return; state.deferredPrompt.prompt(); await state.deferredPrompt.userChoice; state.deferredPrompt=null; $('installBtn').classList.add('hidden'); }; if('serviceWorker' in navigator){ navigator.serviceWorker.register('sw.js').catch(()=>{}); } }
init();
