
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const cvs=$("#mainCanvas"), ctx=cvs.getContext("2d",{willReadFrequently:true});
const state={img:null,baseData:null,mask:null,tool:"move",history:[],layers:[],crop:null,cropping:false,magic:false,colors:["#151331","#3d32a5","#7358d8","#b493f2","#ed8dff","#2b255c","#5146c8","#9980ee"]};
function status(t){$("#status").textContent=t}
function pushHistory(){if(!state.baseData)return;state.history.push({data:ctx.getImageData(0,0,cvs.width,cvs.height),mask:state.mask?new Int8Array(state.mask):null});if(state.history.length>18)state.history.shift()}
function restoreLast(){const h=state.history.pop();if(!h){status("Nothing to undo.");return}cvs.width=h.data.width;cvs.height=h.data.height;ctx.putImageData(h.data,0,0);state.baseData=ctx.getImageData(0,0,cvs.width,cvs.height);state.mask=h.mask;drawOverlay();status("Undo complete.")}
function loadImg(src){const img=new Image();img.onload=()=>{state.img=img;let max=1200,r=Math.min(max/img.width,max/img.height,1);cvs.width=Math.max(360,Math.round(img.width*r));cvs.height=Math.max(360,Math.round(img.height*r));ctx.fillStyle="#fff";ctx.fillRect(0,0,cvs.width,cvs.height);ctx.drawImage(img,0,0,cvs.width,cvs.height);state.baseData=ctx.getImageData(0,0,cvs.width,cvs.height);state.mask=new Int8Array(cvs.width*cvs.height);state.layers=[];renderLayers();status("Image loaded. Crop or Magic Select before generating.")};img.src=src}
$("#imageInput").onchange=e=>{const f=e.target.files?.[0];if(f)loadImg(URL.createObjectURL(f))};
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");["photoPanel","ideaPanel","settingsPanel"].forEach(id=>$("#"+id).classList.add("hidden"));$("#"+b.dataset.panel).classList.remove("hidden")});
$$(".mask").forEach(b=>b.onclick=()=>{$$(".mask").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tool=b.dataset.tool;state.magic=false;state.cropping=false});
["brushSize","contrast","brightness","smoothing","detailBoost","minIsland","bridgeThickness"].forEach(id=>{$("#"+id).oninput=e=>{const m={brushSize:"brushVal",contrast:"contrastVal",brightness:"brightVal",smoothing:"smoothVal",detailBoost:"detailVal",minIsland:"islandVal",bridgeThickness:"bridgeVal"};$("#"+m[id]).textContent=e.target.value}});
$("#undoBtn").onclick=restoreLast; $("#resetBtn").onclick=()=>{if(state.img)loadImg(state.img.src)};
$("#cropToolBtn").onclick=()=>{state.cropping=true;state.magic=false;state.crop=null;$("#applyCropBtn").classList.remove("hidden");$("#cancelCropBtn").classList.remove("hidden");status("Drag a box around the area to keep, then tap Apply Crop.")};
$("#cancelCropBtn").onclick=()=>{state.cropping=false;state.crop=null;drawOverlay();$("#applyCropBtn").classList.add("hidden");$("#cancelCropBtn").classList.add("hidden")};
$("#applyCropBtn").onclick=applyCrop; $("#magicToolBtn").onclick=()=>{state.magic=true;state.cropping=false;status("Tap the subject or area you want to keep. Magic Select works best with simple backgrounds.")};
function pos(e){const r=cvs.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:Math.round((t.clientX-r.left)*cvs.width/r.width),y:Math.round((t.clientY-r.top)*cvs.height/r.height)}}
let down=false,start=null;
function pointerDown(e){if(!state.baseData)return;e.preventDefault();down=true;start=pos(e);if(state.cropping){state.crop={x:start.x,y:start.y,w:1,h:1};drawOverlay();return}if(state.magic){pushHistory();magicSelect(start.x,start.y);state.magic=false;drawOverlay();return}if(state.tool!=="move"){pushHistory();paintMask(start.x,start.y,state.tool==="keep"?1:-1)}}
function pointerMove(e){if(!down||!state.baseData)return;e.preventDefault();const p=pos(e);if(state.cropping&&state.crop){state.crop={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.abs(p.x-start.x),h:Math.abs(p.y-start.y)};drawOverlay();return}if(state.tool!=="move")paintMask(p.x,p.y,state.tool==="keep"?1:-1)}
function pointerUp(){down=false}
cvs.addEventListener("mousedown",pointerDown);cvs.addEventListener("touchstart",pointerDown,{passive:false});cvs.addEventListener("mousemove",pointerMove);cvs.addEventListener("touchmove",pointerMove,{passive:false});["mouseup","mouseleave","touchend"].forEach(ev=>cvs.addEventListener(ev,pointerUp));
function paintMask(x,y,val){const r=+$("#brushSize").value,w=cvs.width,h=cvs.height;for(let yy=Math.max(0,y-r);yy<Math.min(h,y+r);yy++)for(let xx=Math.max(0,x-r);xx<Math.min(w,x+r);xx++)if((xx-x)**2+(yy-y)**2<=r*r)state.mask[yy*w+xx]=val;drawOverlay()}
function drawOverlay(){if(!state.baseData)return;ctx.putImageData(state.baseData,0,0);const img=ctx.getImageData(0,0,cvs.width,cvs.height);if(state.mask){for(let i=0;i<state.mask.length;i++){const p=i*4;if(state.mask[i]===1){img.data[p]=25;img.data[p+1]=220;img.data[p+2]=90;img.data[p+3]=170}else if(state.mask[i]===-1){img.data[p]=255;img.data[p+1]=45;img.data[p+2]=55;img.data[p+3]=160}}ctx.putImageData(img,0,0)}if(state.crop){ctx.save();ctx.strokeStyle="#8a55ff";ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.strokeRect(state.crop.x,state.crop.y,state.crop.w,state.crop.h);ctx.restore()}}
function applyCrop(){if(!state.crop||state.crop.w<20||state.crop.h<20){status("Crop box too small.");return}pushHistory();const c=state.crop;const data=ctx.getImageData(c.x,c.y,c.w,c.h);cvs.width=c.w;cvs.height=c.h;ctx.putImageData(data,0,0);state.baseData=ctx.getImageData(0,0,cvs.width,cvs.height);state.mask=new Int8Array(cvs.width*cvs.height);state.crop=null;state.cropping=false;$("#applyCropBtn").classList.add("hidden");$("#cancelCropBtn").classList.add("hidden");status("Crop applied.")}
function magicSelect(sx,sy){const data=state.baseData.data,w=cvs.width,h=cvs.height,idx=(sy*w+sx)*4,seed=[data[idx],data[idx+1],data[idx+2]],q=[sx,sy],seen=new Uint8Array(w*h);let qi=0,tol=80,count=0;while(qi<q.length&&count<w*h*.72){const x=q[qi++],y=q[qi++];if(x<0||y<0||x>=w||y>=h)continue;const id=y*w+x;if(seen[id])continue;seen[id]=1;const p=id*4,d=Math.abs(data[p]-seed[0])+Math.abs(data[p+1]-seed[1])+Math.abs(data[p+2]-seed[2]);if(d>tol)continue;state.mask[id]=1;count++;q.push(x+1,y,x-1,y,x,y+1,x,y-1)}status("Magic selection added. Use Keep/Remove brush to refine.")}
function adjustedGray(){const d=state.baseData,w=cvs.width,h=cvs.height,out=new Float32Array(w*h),con=1+(+$("#contrast").value/80),bri=+$("#brightness").value;for(let i=0;i<w*h;i++){const p=i*4;let v=.299*d.data[p]+.587*d.data[p+1]+.114*d.data[p+2];v=(v-128)*con+128+bri;if(state.mask?.[i]===-1)v=255;out[i]=Math.max(0,Math.min(255,v))}return out}
function blur(src,w,h,r){if(r<=0)return src.slice();let tmp=new Float32Array(src.length),out=new Float32Array(src.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-r;k<=r;k++){let xx=Math.max(0,Math.min(w-1,x+k));s+=src[y*w+xx];n++}tmp[y*w+x]=s/n}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-r;k<=r;k++){let yy=Math.max(0,Math.min(h-1,y+k));s+=tmp[yy*w+x];n++}out[y*w+x]=s/n}return out}
function edges(gray,w,h){let e=new Float32Array(w*h);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=y*w+x,gx=-gray[i-w-1]-2*gray[i-1]-gray[i+w-1]+gray[i-w+1]+2*gray[i+1]+gray[i+w+1],gy=-gray[i-w-1]-2*gray[i-w]-gray[i-w+1]+gray[i+w-1]+2*gray[i+w]+gray[i+w+1];e[i]=Math.min(255,Math.hypot(gx,gy))}return e}
function clean(bin,w,h,reps){let a=bin,b=new Uint8Array(bin.length);for(let r=0;r<reps;r++){for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let n=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)n+=a[(y+yy)*w+x+xx];b[y*w+x]=n>=5?1:0}[a,b]=[b,a];b.fill(0)}return a}
function processIslands(bin,w,h){const min=+$("#minIsland").value,bridge=+$("#bridgeThickness").value,seen=new Uint8Array(w*h),comps=[];for(let i=0;i<w*h;i++){if(!bin[i]||seen[i])continue;let q=[i],qi=0,pix=[],sx=0,sy=0,minx=w,miny=h,maxx=0,maxy=0;seen[i]=1;while(qi<q.length){let id=q[qi++],x=id%w,y=Math.floor(id/w);pix.push(id);sx+=x;sy+=y;minx=Math.min(minx,x);miny=Math.min(miny,y);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y);[1,-1,w,-w].forEach(o=>{let ni=id+o,nx=ni%w,ny=Math.floor(ni/w);if(ni>=0&&ni<w*h&&Math.abs(nx-x)+Math.abs(ny-y)===1&&bin[ni]&&!seen[ni]){seen[ni]=1;q.push(ni)}})}comps.push({pix,count:pix.length,cx:sx/pix.length,cy:sy/pix.length,minx,miny,maxx,maxy})}if(!comps.length)return bin;comps.sort((a,b)=>b.count-a.count);let out=new Uint8Array(bin.length);comps.forEach((c,i)=>{if(i===0||!$("#removeSmall").checked||c.count>=min)c.pix.forEach(p=>out[p]=1)});if(bridge>0&&comps.length>1){let main=comps[0];for(let i=1;i<comps.length;i++){let c=comps[i];if(c.count<min)continue;let tx=Math.max(main.minx,Math.min(main.maxx,c.cx)),ty=Math.max(main.miny,Math.min(main.maxy,c.cy));drawLine(out,w,h,c.cx,c.cy,tx,ty,Math.max(1,Math.round(bridge/3)))}}return out}
function drawLine(bin,w,h,x0,y0,x1,y1,r){let steps=Math.max(Math.abs(x1-x0),Math.abs(y1-y0),1);for(let s=0;s<=steps;s++){let x=Math.round(x0+(x1-x0)*s/steps),y=Math.round(y0+(y1-y0)*s/steps);for(let yy=y-r;yy<=y+r;yy++)for(let xx=x-r;xx<=x+r;xx++)if(xx>=0&&yy>=0&&xx<w&&yy<h&&(xx-x)**2+(yy-y)**2<=r*r)bin[yy*w+xx]=1}}
function generate(){if(!state.baseData){status("Upload image first.");return}let w=cvs.width,h=cvs.height,n=+$("#layerCount").value,gray=adjustedGray(),smoothPx=Math.round(+$("#smoothing").value/18);gray=blur(gray,w,h,smoothPx);let ed=edges(gray,w,h),detail=+$("#detailBoost").value;state.layers=[];for(let l=0;l<n;l++){let low=255-(l+1)*255/n,high=255-l*255/n,bin=new Uint8Array(w*h);for(let i=0;i<w*h;i++){let hit=gray[i]>=low&&gray[i]<high;if(detail&&ed[i]>(105-detail)&&l<Math.ceil(n*.55))hit=true;if(state.mask?.[i]===-1)hit=false;bin[i]=hit?1:0}if($("#edgeClean").checked)bin=clean(bin,w,h,Math.max(1,Math.round(+$("#smoothing").value/25)));bin=processIslands(bin,w,h);state.layers.push({name:`Layer ${l+1}`,color:state.colors[l%state.colors.length],bin,w,h,visible:true})}renderLayers();status(`Generated ${n} cleaner stencil layers.`)}
$("#generateBtn").onclick=generate;
function renderLayers(){const lc=$("#layerControls"),pr=$("#previews");lc.innerHTML="";pr.innerHTML="";state.layers.forEach((ly,i)=>{let row=document.createElement("div");row.className="layerRow";row.innerHTML=`<div class="swatch" style="background:${ly.color}"></div><div><b>${ly.name}</b><br><small>${i===0?"Darkest":i===state.layers.length-1?"Lightest":"Tone"}</small></div><button class="eye">${ly.visible?"◉":"○"}</button>`;row.querySelector(".swatch").onclick=()=>{let inp=document.createElement("input");inp.type="color";inp.value=ly.color;inp.oninput=()=>{ly.color=inp.value;renderLayers()};inp.click()};row.querySelector(".eye").onclick=()=>{ly.visible=!ly.visible;renderLayers()};lc.appendChild(row);if(ly.visible){let card=document.createElement("div");card.className="preview";let c=document.createElement("canvas");c.width=ly.w;c.height=ly.h;drawLayerCanvas(c,ly);card.appendChild(c);let p=document.createElement("p");p.textContent=ly.name;card.appendChild(p);pr.appendChild(card)}})}
function drawLayerCanvas(c,ly){let g=c.getContext("2d");g.clearRect(0,0,c.width,c.height);if($("#showBg").checked){g.fillStyle="#fff";g.fillRect(0,0,c.width,c.height)}g.fillStyle=ly.color;g.filter=`blur(${Math.max(0,+$("#smoothing").value/45)}px)`;let path=new Path2D();for(let y=0;y<ly.h;y++){let x=0;while(x<ly.w){while(x<ly.w&&!ly.bin[y*ly.w+x])x++;if(x>=ly.w)break;let x0=x;while(x<ly.w&&ly.bin[y*ly.w+x])x++;path.rect(x0,y,x-x0,1)}}g.fill(path);g.filter="none";if($("#registration").checked)drawReg(g,ly.w,ly.h)}
function drawReg(g,w,h){g.strokeStyle="#111";g.lineWidth=Math.max(3,w/250);let s=Math.max(20,w/32);[[s,s],[w-s,s],[s,h-s],[w-s,h-s]].forEach(([x,y])=>{g.beginPath();g.moveTo(x-s/2,y);g.lineTo(x+s/2,y);g.moveTo(x,y-s/2);g.lineTo(x,y+s/2);g.stroke()})}
function svgRects(ly){let rects=[],step=2,rx=Math.max(.5,+$("#smoothing").value/80);for(let y=0;y<ly.h;y+=step){let x=0;while(x<ly.w){while(x<ly.w&&!ly.bin[y*ly.w+x])x+=step;if(x>=ly.w)break;let x0=x;while(x<ly.w&&ly.bin[y*ly.w+x])x+=step;rects.push(`<rect x="${x0}" y="${y}" width="${x-x0}" height="${step}" rx="${rx}" ry="${rx}"/>`)}}return rects.join("")}
function regSvg(w,h){let s=Math.max(20,w/32),sw=Math.max(3,w/250),o="";[[s,s],[w-s,s],[s,h-s],[w-s,h-s]].forEach(([x,y])=>{o+=`<path d="M${x-s/2} ${y}L${x+s/2} ${y}M${x} ${y-s/2}L${x} ${y+s/2}" stroke="#111" stroke-width="${sw}" fill="none"/>`});return o}
function svgFor(ly){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${ly.w} ${ly.h}" width="${ly.w}" height="${ly.h}"><title>${ly.name}</title><g fill="${ly.color}" stroke="none">${svgRects(ly)}</g>${$("#registration").checked?regSvg(ly.w,ly.h):""}</svg>`}
function safe(){return ($("#projectName").value||"stencilforge_project").toLowerCase().replace(/[^a-z0-9_-]+/g,"_")}
function dl(name,text,type="image/svg+xml"){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#downloadLayersBtn").onclick=()=>{let ls=state.layers.filter(l=>l.visible);if(!ls.length){status("Generate layers first.");return}ls.forEach((l,i)=>setTimeout(()=>dl(`${safe()}_${l.name.replace(/\s+/g,"_").toLowerCase()}.svg`,svgFor(l)),i*220));status("Downloading individual SVG layer files.")}
$("#downloadCombinedBtn").onclick=()=>{let ls=state.layers.filter(l=>l.visible);if(!ls.length){status("Generate layers first.");return}let w=ls[0].w,h=ls[0].h,body=ls.map(l=>`<g id="${l.name.replace(/\s+/g,"_")}" fill="${l.color}">${svgRects(l)}</g>`).join("\n");dl(`${safe()}_combined.svg`,`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">${body}${$("#registration").checked?regSvg(w,h):""}</svg>`)}
$("#saveBtn").onclick=()=>{localStorage.setItem("stencilforge_v3",JSON.stringify({name:$("#projectName").value,settings:{layerCount:$("#layerCount").value,preset:$("#preset").value,contrast:$("#contrast").value,brightness:$("#brightness").value,smoothing:$("#smoothing").value,detailBoost:$("#detailBoost").value,minIsland:$("#minIsland").value,bridgeThickness:$("#bridgeThickness").value}}));status("Project settings saved.")}
$("#loadBtn").onclick=()=>{let p=JSON.parse(localStorage.getItem("stencilforge_v3")||"null");if(!p){status("No saved project found.");return}$("#projectName").value=p.name||"stencilforge_project";Object.entries(p.settings||{}).forEach(([k,v])=>{let el=$("#"+k);if(el){el.value=v;el.dispatchEvent(new Event("input"))}});status("Project settings loaded.")}
$("#ideaBtn").onclick=()=>{let text=$("#ideaText").value||"cute stencil creature";let c=document.createElement("canvas");c.width=900;c.height=900;let g=c.getContext("2d");g.fillStyle="#fff";g.fillRect(0,0,900,900);g.fillStyle="#d97cff";g.beginPath();g.arc(185,185,32,0,7);g.fill();g.fillStyle="#4d3fb7";g.beginPath();g.ellipse(455,455,185,245,0,0,7);g.fill();g.fillStyle="#8f6bff";g.beginPath();g.ellipse(455,330,150,115,0,0,7);g.fill();g.fillStyle="#4d3fb7";g.beginPath();g.moveTo(335,280);g.lineTo(285,120);g.lineTo(410,245);g.moveTo(575,280);g.lineTo(625,120);g.lineTo(500,245);g.fill();g.fillStyle="#fff";g.beginPath();g.arc(405,330,28,0,7);g.arc(505,330,28,0,7);g.fill();g.fillStyle="#21183f";g.beginPath();g.arc(405,330,12,0,7);g.arc(505,330,12,0,7);g.fill();g.strokeStyle="#21183f";g.lineWidth=18;g.beginPath();g.moveTo(325,500);g.quadraticCurveTo(180,380,140,620);g.moveTo(585,500);g.quadraticCurveTo(730,380,770,620);g.stroke();g.fillStyle="#4d3fb7";g.font="bold 32px system-ui";g.textAlign="center";g.fillText(text.slice(0,48),450,840);loadImg(c.toDataURL())}
let deferred=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").hidden=false});$("#installBtn").onclick=()=>{if(deferred){deferred.prompt();deferred=null;$("#installBtn").hidden=true}};if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
